apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  lables: 
    {{- include "cart-nodejs.labels" . | nindent 4}}
spec:
  selector:
    {{- include "cart-nodejs.selectorLabels" . | nindent 4}}
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    name: http