apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: react-ui
spec:
  selector:
    app: react-ui
  ports:
  - port: 8080
    targetPort: 8080
    type: NodePort
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-ui
spec:
  selector:
    matchLabels:
      app: react-ui
  template:
    metadata:
      labels:
        app: react-ui
    spec:
      containers:
      - name: react-ui
        image: val418orant/ui-reactjs:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080