apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
    {{- include "api-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "api-gateway.selectorLabels" . | nindent 8 }}
    spec: 
      containers:
      - name: {{ .Values.deployment.name }}
        image: {{ .Values.deployment.image }}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: {{ .Values.service.targetPort }}