apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels: 
    {{- include "api-gateway.labels" . | nindent 4}}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "api-gateway.selectorLabels" . | nindent 4}}
  ports:
  - port: {{ .Values.service.port}}
    targetPort: {{ .Values.service.targetPort}}
    nodePort: {{ .Values.service.nodePort}}