apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "wishlist-python.labels" . | nindent 4 }}
  name: {{ .Values.deployment.name }}
spec:
  selector:
    matchLabels:
      {{- include "wishlist-python.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wishlist-python.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.deployment.name }}
        image: {{ .Values.deployment.image }}
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: {{ .Values.service.targetPort }}
