apiVersion: v1
kind: Service
metadata:
  name: wishlist
  labels:
    app: wishlist-ui
spec:
  selector:
    app: wishlist-ui
  ports:
  - port: 1003
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-ui
spec:
  selector:
    matchLabels:
      app: wishlist-ui
  template:
    metadata:
      labels:
        app: wishlist-ui
    spec:
      containers:
      - name: shoe-ui
        image: val418orant/shoes:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
